# Generated by Django 5.2.17 on 2026-08-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySDOH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tract_fips', models.CharField(db_index=True, help_text='11-digit zero-padded Census Tract FIPS code (e.g. 06001400200)', max_length=11, unique=True)),
                ('county', models.CharField(blank=True, help_text='County name', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='CA', help_text='State abbreviation (California only)', max_length=50, null=True)),
                ('poverty_2018', models.FloatField(blank=True, null=True)),
                ('poverty_2020', models.FloatField(blank=True, null=True)),
                ('poverty_2022', models.FloatField(blank=True, null=True)),
                ('poverty_change_20_22', models.FloatField(blank=True, null=True)),
                ('poverty_change_trend', models.CharField(blank=True, max_length=50, null=True)),
                ('income_2018', models.FloatField(blank=True, null=True)),
                ('income_2020', models.FloatField(blank=True, null=True)),
                ('income_2022', models.FloatField(blank=True, null=True)),
                ('income_change_20_22', models.FloatField(blank=True, null=True)),
                ('income_change_trend', models.CharField(blank=True, max_length=50, null=True)),
                ('unemployment_2018', models.FloatField(blank=True, null=True)),
                ('unemployment_2020', models.FloatField(blank=True, null=True)),
                ('unemployment_2022', models.FloatField(blank=True, null=True)),
                ('unemployment_change_20_22', models.FloatField(blank=True, null=True)),
                ('unemployment_change_trend', models.CharField(blank=True, max_length=50, null=True)),
                ('education_2018', models.FloatField(blank=True, null=True)),
                ('education_2020', models.FloatField(blank=True, null=True)),
                ('education_2022', models.FloatField(blank=True, null=True)),
                ('education_change_20_22', models.FloatField(blank=True, null=True)),
                ('education_change_trend', models.CharField(blank=True, max_length=50, null=True)),
                ('housing_burden_2018', models.FloatField(blank=True, null=True)),
                ('housing_burden_2020', models.FloatField(blank=True, null=True)),
                ('housing_burden_2022', models.FloatField(blank=True, null=True)),
                ('housing_burden_change_20_22', models.FloatField(blank=True, null=True)),
                ('housing_burden_change_trend', models.CharField(blank=True, max_length=50, null=True)),
                ('no_vehicle_2018', models.FloatField(blank=True, null=True)),
                ('no_vehicle_2020', models.FloatField(blank=True, null=True)),
                ('no_vehicle_2022', models.FloatField(blank=True, null=True)),
                ('no_vehicle_change_20_22', models.FloatField(blank=True, null=True)),
                ('no_vehicle_change_trend', models.CharField(blank=True, max_length=50, null=True)),
                ('food_access_population_2018', models.FloatField(blank=True, null=True)),
                ('food_access_population_2020', models.FloatField(blank=True, null=True)),
                ('food_access_population_2022', models.FloatField(blank=True, null=True)),
                ('food_access_population_change_20_22', models.FloatField(blank=True, null=True)),
                ('food_access_population_change_trend', models.CharField(blank=True, max_length=50, null=True)),
                ('uninsured_2018', models.FloatField(blank=True, null=True)),
                ('uninsured_2020', models.FloatField(blank=True, null=True)),
                ('uninsured_2022', models.FloatField(blank=True, null=True)),
                ('uninsured_change_20_22', models.FloatField(blank=True, null=True)),
                ('uninsured_change_trend', models.CharField(blank=True, max_length=50, null=True)),
                ('disability_2018', models.FloatField(blank=True, null=True)),
                ('disability_2020', models.FloatField(blank=True, null=True)),
                ('disability_2022', models.FloatField(blank=True, null=True)),
                ('disability_change_20_22', models.FloatField(blank=True, null=True)),
                ('disability_change_trend', models.CharField(blank=True, max_length=50, null=True)),
                ('broadband_2018', models.FloatField(blank=True, null=True)),
                ('broadband_2020', models.FloatField(blank=True, null=True)),
                ('broadband_2022', models.FloatField(blank=True, null=True)),
                ('broadband_change_20_22', models.FloatField(blank=True, null=True)),
                ('broadband_change_trend', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Community SDOH',
                'verbose_name_plural': 'Community SDOH Records',
                'db_table': 'community_sdoh',
                'ordering': ['tract_fips'],
            },
        ),
    ]
