# Generated by Django 5.2.17 on 2026-08-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdoh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(db_index=True, help_text='Unique patient identifier (string)', max_length=64, unique=True)),
                ('snapshot_date', models.DateField(blank=True, help_text='Date of snapshot / encounter summary', null=True)),
                ('tract_fips', models.CharField(db_index=True, help_text='11-digit zero-padded Census Tract FIPS code', max_length=11)),
                ('encounters_last_12m', models.FloatField(blank=True, null=True)),
                ('inpatient_admissions_last_12m', models.FloatField(blank=True, null=True)),
                ('emergency_visits_last_12m', models.FloatField(blank=True, null=True)),
                ('outpatient_visits_last_12m', models.FloatField(blank=True, null=True)),
                ('conditions_last_12m', models.FloatField(blank=True, null=True)),
                ('chronic_conditions_last_12m', models.FloatField(blank=True, null=True)),
                ('medications_last_12m', models.FloatField(blank=True, null=True)),
                ('procedures_last_12m', models.FloatField(blank=True, null=True)),
                ('clinical_burden_last_12m', models.FloatField(blank=True, null=True)),
                ('healthcare_utilization_last_12m', models.FloatField(blank=True, null=True)),
                ('medications_per_encounter_last_12m', models.FloatField(blank=True, null=True)),
                ('conditions_per_encounter_last_12m', models.FloatField(blank=True, null=True)),
                ('change_recent_vs_previous_encounters', models.FloatField(blank=True, null=True)),
                ('growth_recent_vs_previous_encounters', models.FloatField(blank=True, null=True)),
                ('change_recent_vs_previous_conditions', models.FloatField(blank=True, null=True)),
                ('growth_recent_vs_previous_conditions', models.FloatField(blank=True, null=True)),
                ('change_recent_vs_previous_chronic_conditions', models.FloatField(blank=True, null=True)),
                ('growth_recent_vs_previous_chronic_conditions', models.FloatField(blank=True, null=True)),
                ('change_recent_vs_previous_medications', models.FloatField(blank=True, null=True)),
                ('growth_recent_vs_previous_medications', models.FloatField(blank=True, null=True)),
                ('change_recent_vs_previous_procedures', models.FloatField(blank=True, null=True)),
                ('growth_recent_vs_previous_procedures', models.FloatField(blank=True, null=True)),
                ('change_recent_vs_previous_clinical_burden', models.FloatField(blank=True, null=True)),
                ('growth_recent_vs_previous_clinical_burden', models.FloatField(blank=True, null=True)),
                ('change_recent_vs_previous_healthcare_utilization', models.FloatField(blank=True, null=True)),
                ('growth_recent_vs_previous_healthcare_utilization', models.FloatField(blank=True, null=True)),
                ('gender_f', models.FloatField(blank=True, null=True)),
                ('gender_m', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patient',
                'ordering': ['patient_id'],
            },
        ),
    ]
