# Generated by Django 5.2.17 on 2026-08-16 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdoh', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRiskPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tract_fips', models.CharField(db_index=True, help_text='Patient Census Tract FIPS', max_length=11)),
                ('current_risk_class', models.IntegerField(blank=True, help_text='Current risk predicted class integer: 0=Very Low, 1=Low, 2=Moderate, 3=High, 4=Critical', null=True)),
                ('current_risk_level', models.CharField(blank=True, help_text="Current risk level name: 'Very Low', 'Low', 'Moderate', 'High', 'Critical'", max_length=20, null=True)),
                ('current_risk_confidence', models.FloatField(blank=True, help_text='Confidence probability of current risk predicted class', null=True)),
                ('current_risk_probabilities', models.JSONField(blank=True, help_text='5-class probability distribution dictionary', null=True)),
                ('future_risk_class', models.IntegerField(blank=True, help_text='Future risk predicted class integer: 0=Low, 1=Moderate, 2=High', null=True)),
                ('future_risk_level', models.CharField(blank=True, help_text="Future risk level name: 'Low', 'Moderate', 'High'", max_length=20, null=True)),
                ('future_risk_confidence', models.FloatField(blank=True, help_text='Confidence probability of future risk predicted class', null=True)),
                ('future_risk_probabilities', models.JSONField(blank=True, help_text='3-class probability distribution dictionary', null=True)),
                ('intervention_priority', models.CharField(blank=True, help_text='Intervention priority headline based on current risk', max_length=50, null=True)),
                ('future_forecast_note', models.CharField(blank=True, help_text='Forecasting note regarding future risk trend', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(help_text='Associated Patient record', on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='sdoh.patient')),
            ],
            options={
                'verbose_name': 'Patient Risk Prediction',
                'verbose_name_plural': 'Patient Risk Predictions',
                'db_table': 'patient_risk_prediction',
                'ordering': ['-created_at'],
            },
        ),
    ]
