# Generated by Django 5.2.17 on 2026-08-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdoh', '0003_patientriskprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientriskprediction',
            name='driver_type',
            field=models.CharField(blank=True, help_text="Dominant risk driver category: 'Clinical', 'SDOH', or 'Combined'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientriskprediction',
            name='input_data_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of predictive input features for change detection', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='patientriskprediction',
            name='model_name',
            field=models.CharField(default='sdoh_catboost_future_risk_model.cbm', help_text='Name of the deployed ML model', max_length=100),
        ),
        migrations.AddField(
            model_name='patientriskprediction',
            name='model_version',
            field=models.CharField(db_index=True, default='catboost_v1', help_text='Model release version tag for cache invalidation', max_length=50),
        ),
        migrations.AddField(
            model_name='patientriskprediction',
            name='predicted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patientriskprediction',
            name='primary_driver',
            field=models.CharField(blank=True, help_text='Primary feature driver headline formatted with SHAP impact', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientriskprediction',
            name='primary_shap_value',
            field=models.FloatField(blank=True, help_text='Numeric SHAP attribution value of the primary driver', null=True),
        ),
        migrations.AddField(
            model_name='patientriskprediction',
            name='shap_drivers',
            field=models.JSONField(blank=True, help_text='Full top-5 TreeSHAP feature attribution array with rank, category, and exact SHAP impact', null=True),
        ),
        migrations.AlterField(
            model_name='patientriskprediction',
            name='current_risk_class',
            field=models.IntegerField(blank=True, help_text='5-class Future risk predicted class integer: 0=Very Low, 1=Low, 2=Moderate, 3=High, 4=Critical', null=True),
        ),
        migrations.AlterField(
            model_name='patientriskprediction',
            name='current_risk_confidence',
            field=models.FloatField(blank=True, help_text='Confidence probability of 5-class Future risk predicted class', null=True),
        ),
        migrations.AlterField(
            model_name='patientriskprediction',
            name='current_risk_level',
            field=models.CharField(blank=True, help_text="5-class Future risk level name: 'Very Low', 'Low', 'Moderate', 'High', 'Critical'", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientriskprediction',
            name='current_risk_probabilities',
            field=models.JSONField(blank=True, help_text='5-class Future risk probability distribution dictionary', null=True),
        ),
        migrations.AlterField(
            model_name='patientriskprediction',
            name='future_forecast_note',
            field=models.CharField(blank=True, help_text='Forecasting note comparing 5-class and 3-class future risk trends', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientriskprediction',
            name='future_risk_class',
            field=models.IntegerField(blank=True, help_text='3-class Future risk predicted class integer: 0=Low, 1=Moderate, 2=High', null=True),
        ),
        migrations.AlterField(
            model_name='patientriskprediction',
            name='future_risk_confidence',
            field=models.FloatField(blank=True, help_text='Confidence probability of 3-class Future risk predicted class', null=True),
        ),
        migrations.AlterField(
            model_name='patientriskprediction',
            name='future_risk_level',
            field=models.CharField(blank=True, help_text="3-class Future risk level name: 'Low', 'Moderate', 'High'", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientriskprediction',
            name='future_risk_probabilities',
            field=models.JSONField(blank=True, help_text='3-class Future risk probability distribution dictionary', null=True),
        ),
        migrations.AlterField(
            model_name='patientriskprediction',
            name='intervention_priority',
            field=models.CharField(blank=True, help_text='Intervention priority headline based on 5-class future risk', max_length=100, null=True),
        ),
    ]
