# Generated by Django 5.2.17 on 2026-08-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdoh', '0004_patientriskprediction_driver_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Patient full name', max_length=150),
        ),
    ]
