# Generated by Django 5.2.17 on 2026-08-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdoh', '0005_patient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentCommunity',
            fields=[
                ('state_abbreviation', models.CharField(blank=True, default='', max_length=10)),
                ('state_county_fips', models.CharField(db_index=True, max_length=10)),
                ('county_name', models.CharField(blank=True, default='', max_length=100)),
                ('tract_fips', models.CharField(db_index=True, help_text='11-digit zero-padded Census Tract FIPS code', max_length=11, primary_key=True, serialize=False, unique=True)),
                ('tract_id', models.CharField(db_index=True, max_length=20)),
                ('social_vulnerability_index', models.FloatField(blank=True, null=True)),
                ('poverty_rate', models.FloatField(blank=True, null=True)),
                ('median_household_income', models.FloatField(blank=True, null=True)),
                ('uninsured_rate', models.FloatField(blank=True, null=True)),
                ('housing_cost_burden', models.FloatField(blank=True, null=True)),
                ('no_vehicle_rate', models.FloatField(blank=True, null=True)),
                ('low_access_households_no_vehicle', models.FloatField(blank=True, null=True)),
                ('low_access_population_rate', models.FloatField(blank=True, null=True)),
                ('disability_rate', models.FloatField(blank=True, null=True)),
                ('unemployment_rate', models.FloatField(blank=True, null=True)),
                ('no_internet_access_rate', models.FloatField(blank=True, null=True)),
                ('limited_english_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Current Community',
                'verbose_name_plural': 'Current Community Records',
                'db_table': 'current_community',
                'ordering': ['tract_fips'],
                'indexes': [models.Index(fields=['tract_fips'], name='current_com_tract_f_e7b8f1_idx'), models.Index(fields=['tract_id'], name='current_com_tract_i_e0028b_idx'), models.Index(fields=['state_county_fips'], name='current_com_state_c_6acefe_idx')],
            },
        ),
        migrations.CreateModel(
            name='CurrentPatient',
            fields=[
                ('PATIENT_ID', models.CharField(db_index=True, help_text='Unique patient identifier', max_length=64, primary_key=True, serialize=False, unique=True)),
                ('PATIENT_NAME', models.CharField(blank=True, default='', max_length=150)),
                ('FIPS_ID', models.CharField(db_index=True, help_text='11-digit Census Tract FIPS code', max_length=11)),
                ('STATE_NAME', models.CharField(blank=True, default='', max_length=100)),
                ('AGE', models.IntegerField(blank=True, null=True)),
                ('GENDER', models.CharField(blank=True, default='', max_length=20)),
                ('CHRONIC_CONDITIONS', models.IntegerField(blank=True, null=True)),
                ('CONDITIONS', models.IntegerField(blank=True, null=True)),
                ('INPATIENT_ADMISSIONS', models.IntegerField(blank=True, null=True)),
                ('EMERGENCY_VISITS', models.IntegerField(blank=True, null=True)),
                ('OUTPATIENT_VISITS', models.IntegerField(blank=True, null=True)),
                ('MEDICATIONS', models.IntegerField(blank=True, null=True)),
                ('PROCEDURES', models.IntegerField(blank=True, null=True)),
                ('MEDICATIONS_PER_ENCOUNTER', models.FloatField(blank=True, null=True)),
                ('CONDITIONS_PER_ENCOUNTER', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Current Patient',
                'verbose_name_plural': 'Current Patients',
                'db_table': 'current_patient',
                'ordering': ['PATIENT_ID'],
                'indexes': [models.Index(fields=['PATIENT_ID'], name='current_pat_PATIENT_70632a_idx'), models.Index(fields=['FIPS_ID'], name='current_pat_FIPS_ID_38f699_idx')],
            },
        ),
    ]
