# Generated by Django 5.2.17 on 2026-08-17 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdoh', '0006_currentcommunity_currentpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentcommunity',
            name='community_risk_level',
            field=models.CharField(blank=True, help_text='Community Risk Category (e.g. LOW, MEDIUM, etc.)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='currentcommunity',
            name='community_risk_score',
            field=models.FloatField(blank=True, help_text='Community Risk Score (0-100 continuous)', null=True),
        ),
        migrations.AddField(
            model_name='currentcommunity',
            name='feature_contribution_percentages',
            field=models.JSONField(blank=True, help_text='Preserves SDOH feature contribution percentages', null=True),
        ),
        migrations.AddField(
            model_name='currentcommunity',
            name='normalized_values',
            field=models.JSONField(blank=True, help_text='Preserves normalized SDOH values', null=True),
        ),
        migrations.AddField(
            model_name='currentcommunity',
            name='risk_oriented_values',
            field=models.JSONField(blank=True, help_text='Preserves risk-direction-transformed SDOH values', null=True),
        ),
        migrations.CreateModel(
            name='CurrentPatientPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tract_fips', models.CharField(db_index=True, help_text='Patient Census Tract FIPS', max_length=11)),
                ('prediction_timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the prediction was evaluated')),
                ('clinical_risk_score', models.FloatField(help_text='Continuous Clinical Risk Score (0-100)')),
                ('clinical_risk_level', models.CharField(help_text='Predicted clinical risk level (e.g. LOW)', max_length=20)),
                ('clinical_probability_very_low', models.FloatField()),
                ('clinical_probability_low', models.FloatField()),
                ('clinical_probability_medium', models.FloatField()),
                ('clinical_probability_high', models.FloatField()),
                ('clinical_probability_very_high', models.FloatField()),
                ('community_risk_score', models.FloatField(help_text='Continuous Community Risk Score (0-100)')),
                ('community_risk_level', models.CharField(help_text='Predicted community risk level (e.g. MEDIUM)', max_length=20)),
                ('final_current_risk_score', models.FloatField(help_text='Combined Current Risk Score (0-100)')),
                ('final_current_risk_level', models.CharField(help_text='Combined risk category (e.g. HIGH)', max_length=20)),
                ('model_version', models.CharField(default='xgboost_v1', max_length=50)),
                ('raw_sdoh_values', models.JSONField(help_text='Original raw community feature values')),
                ('normalized_sdoh_values', models.JSONField(help_text='Normalized community feature values')),
                ('risk_oriented_sdoh_values', models.JSONField(help_text='Risk-direction-transformed community values')),
                ('sdoh_feature_contribution_percentages', models.JSONField(help_text='Prevalence contribution percentages')),
                ('clinical_shap_drivers', models.JSONField(blank=True, help_text='Clinical feature SHAP drivers list', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(help_text='Associated current patient record', on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='sdoh.currentpatient')),
            ],
            options={
                'verbose_name': 'Current Patient Risk Prediction',
                'verbose_name_plural': 'Current Patient Risk Predictions',
                'db_table': 'current_patient_prediction',
                'ordering': ['-prediction_timestamp'],
                'indexes': [models.Index(fields=['patient'], name='current_pat_patient_c228ef_idx'), models.Index(fields=['tract_fips'], name='current_pat_tract_f_89b559_idx'), models.Index(fields=['prediction_timestamp'], name='current_pat_predict_45a09c_idx')],
            },
        ),
    ]
