# Generated by Django 5.2.17 on 2026-08-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdoh', '0007_currentcommunity_community_risk_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityInterventionNotification',
            fields=[
                ('notification_id', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('county_fips', models.CharField(db_index=True, max_length=10)),
                ('county_name', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=50)),
                ('primary_driver', models.CharField(max_length=255)),
                ('primary_driver_shap', models.FloatField()),
                ('domain', models.CharField(db_index=True, max_length=100)),
                ('priority', models.CharField(max_length=50)),
                ('intervention', models.TextField()),
                ('reason', models.TextField()),
                ('recipient_email', models.CharField(max_length=255)),
                ('email_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SIMULATED', 'SIMULATED'), ('SENT', 'SENT'), ('ACKNOWLEDGED', 'ACKNOWLEDGED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('RESOLVED', 'RESOLVED'), ('FAILED', 'FAILED')], db_index=True, default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'community_intervention_notification',
            },
        ),
        migrations.CreateModel(
            name='InterventionContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('state_fips', models.CharField(max_length=10)),
                ('county_fips', models.CharField(db_index=True, max_length=10)),
                ('county_name', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('domain', models.CharField(db_index=True, max_length=100)),
                ('contact_role', models.CharField(max_length=200)),
                ('contact_email', models.CharField(max_length=255)),
                ('email_type', models.CharField(max_length=50)),
                ('notification_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'intervention_contact',
                'unique_together': {('county_fips', 'domain')},
            },
        ),
    ]
