# Generated by Django 5.2.17 on 2026-08-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdoh', '0008_communityinterventionnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityinterventionnotification',
            name='ai_email_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityinterventionnotification',
            name='ai_email_subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
